[z-audio-plugin]
name = "Z Audio Simple Synth"

[z-audio-eq-plugin]
name = "Z Audio Simple EQ"

[z-audio-piano-plugin]
name = "Z Audio Formula Piano"

[z-audio-drums-plugin]
name = "Z Audio Formula Drum Set"

[z-audio-reverb-plugin]
name = "Z Audio Parametric Reverb"

[z-audio-diffuser-plugin]
name = "Z Audio Diffuser"

[z-audio-limiter-plugin]
name = "Z Audio Limiter"

[z-audio-compressor-plugin]
name = "Z Audio Compressor"

[z-audio-sampler-plugin]
name = "Z Audio Sampler"
